/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BSlegt (https://sketchfab.com/BSlegt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/football-072a7e8d610f4143aa510256112d97cf
title: Football
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Hedra2_Standardmaterial_0: THREE.Mesh
  }
  materials: {
    Standardmaterial: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/football.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Hedra2_Standardmaterial_0.geometry} material={materials.Standardmaterial} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/football.gltf')
