/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ozhogi (https://sketchfab.com/ozhogi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/headphones-53d859cc3a4e4ad98cf238840b490485
title: Headphones
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
  }
  materials: {
    Headphones: THREE.MeshStandardMaterial
    ['Headphones.002']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/headphone.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.Headphones} />
          <mesh geometry={nodes.Object_7.geometry} material={materials['Headphones.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/headphone.gltf')
